"""Ticker data for companies in INCLUDE_DETAILS that are not yet in ticker_source_map.json.

Each entry: company name (exact key from build_auto_excel) -> dict with ticker, exchange,
data_source (US|Canada|Europe|Japan_Korea|Other), and for non-US: yahoo_symbol, reporting_currency.
Used by merge_ticker_additions.py to update ticker_source_map.json.
"""
from __future__ import annotations

# fmt: off
ADDITIONS: dict[str, dict[str, str]] = {
    # ── Japan (TYO, JPY) ─────────────────────────────────────────────────────
    "AGC INC": {"ticker": "5201", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5201.T", "reporting_currency": "JPY"},
    "AHRESTY CORP": {"ticker": "5852", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5852.T", "reporting_currency": "JPY"},
    "AISAN INDUSTRY CO LTD": {"ticker": "7262", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7262.T", "reporting_currency": "JPY"},
    "AKEBONO BRAKE INDUSTRY CO LTD": {"ticker": "7238", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7238.T", "reporting_currency": "JPY"},
    "ALPS ALPINE CO LTD": {"ticker": "6770", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6770.T", "reporting_currency": "JPY"},
    "BANDO CHEMICAL INDUSTRIES LTD": {"ticker": "9985", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "9985.T", "reporting_currency": "JPY"},
    "DAIDO CORP": {"ticker": "5471", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5471.T", "reporting_currency": "JPY"},
    "DAIDO METAL CO LTD": {"ticker": "7245", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7245.T", "reporting_currency": "JPY"},
    "DIAMOND ELECTRIC HOLDINGS CO LTD": {"ticker": "6646", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6646.T", "reporting_currency": "JPY"},
    "DY CORPORATION": {"ticker": "3942", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "3942.T", "reporting_currency": "JPY"},
    "EXEDY CORPORATION": {"ticker": "7278", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7278.T", "reporting_currency": "JPY"},
    "F-TECH INC": {"ticker": "7212", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7212.T", "reporting_currency": "JPY"},
    "FCC CO LTD": {"ticker": "7296", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7296.T", "reporting_currency": "JPY"},
    "FOSTER ELECTRIC CO LTD": {"ticker": "6799", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6799.T", "reporting_currency": "JPY"},
    "FUJIKURA LTD": {"ticker": "5803", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5803.T", "reporting_currency": "JPY"},
    "FURUKAWA ELECTRIC CO LTD": {"ticker": "5801", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5801.T", "reporting_currency": "JPY"},
    "GMB CORP": {"ticker": "7214", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7214.T", "reporting_currency": "JPY"},
    "HARADA INDUSTRY CO LTD": {"ticker": "6158", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6158.T", "reporting_currency": "JPY"},
    "HOSIDEN CORPORATION": {"ticker": "6804", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6804.T", "reporting_currency": "JPY"},
    "JTEKT CORP": {"ticker": "6473", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6473.T", "reporting_currency": "JPY"},
    "KOBE STEEL LTD": {"ticker": "5406", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5406.T", "reporting_currency": "JPY"},
    "KOITO MANUFACTURING CO LTD": {"ticker": "7276", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7276.T", "reporting_currency": "JPY"},
    "KYB CORP": {"ticker": "7242", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7242.T", "reporting_currency": "JPY"},
    "MINEBEA MITSUMI INC": {"ticker": "6479", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6479.T", "reporting_currency": "JPY"},
    "MITSUBA CORP": {"ticker": "7240", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7240.T", "reporting_currency": "JPY"},
    "MITSUBISHI MATERIALS CORP": {"ticker": "5711", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5711.T", "reporting_currency": "JPY"},
    "MITSUBISHI STEEL MFG CO LTD": {"ticker": "5632", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5632.T", "reporting_currency": "JPY"},
    "MITSUBOSHI BELTING LTD": {"ticker": "5192", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5192.T", "reporting_currency": "JPY"},
    "MURO CORPORATION": {"ticker": "7264", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7264.T", "reporting_currency": "JPY"},
    "MUSASHI SEIMITSU INDUSTRY CO LTD": {"ticker": "7220", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7220.T", "reporting_currency": "JPY"},
    "NHK SPRING CO LTD": {"ticker": "5991", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5991.T", "reporting_currency": "JPY"},
    "NICHIAS CORP": {"ticker": "5942", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5942.T", "reporting_currency": "JPY"},
    "NICHIRIN CO LTD": {"ticker": "5186", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5186.T", "reporting_currency": "JPY"},
    "NIFCO INC": {"ticker": "7988", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7988.T", "reporting_currency": "JPY"},
    "NIPPON SEIKI CO LTD": {"ticker": "6920", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6920.T", "reporting_currency": "JPY"},
    "NIPPON SHEET GLASS CO LTD": {"ticker": "5202", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5202.T", "reporting_currency": "JPY"},
    "NISHIKAWA RUBBER CO LTD": {"ticker": "5161", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5161.T", "reporting_currency": "JPY"},
    "NISSHINBO HOLDINGS INC": {"ticker": "3105", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "3105.T", "reporting_currency": "JPY"},
    "NITERRA CO LTD": {"ticker": "5334", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5334.T", "reporting_currency": "JPY"},
    "NITTO DENKO CORP": {"ticker": "6988", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6988.T", "reporting_currency": "JPY"},
    "NOK CORPORATION": {"ticker": "7240", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7240.T", "reporting_currency": "JPY"},  # Nok Corp (rubber)
    "NSK LTD": {"ticker": "6471", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6471.T", "reporting_currency": "JPY"},
    "OMRON CORPORATION": {"ticker": "6645", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6645.T", "reporting_currency": "JPY"},
    "PACIFIC INDUSTRIAL CO LTD": {"ticker": "7241", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7241.T", "reporting_currency": "JPY"},
    "PIOLAX INC": {"ticker": "7317", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7317.T", "reporting_currency": "JPY"},
    "RYOBI LTD": {"ticker": "5851", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5851.T", "reporting_currency": "JPY"},
    "SANDEN CORPORATION": {"ticker": "6444", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6444.T", "reporting_currency": "JPY"},
    "SANKO GOSEI LTD": {"ticker": "7888", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7888.T", "reporting_currency": "JPY"},
    "SANOH INDUSTRIAL CO LTD": {"ticker": "7196", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7196.T", "reporting_currency": "JPY"},
    "STANLEY ELECTRIC CO LTD": {"ticker": "6923", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6923.T", "reporting_currency": "JPY"},
    "SUMITOMO RIKO COMPANY LTD": {"ticker": "5191", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5191.T", "reporting_currency": "JPY"},
    "T RAD CO LTD": {"ticker": "5857", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5857.T", "reporting_currency": "JPY"},
    "TAIHO KOGYO CO LTD": {"ticker": "7215", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7215.T", "reporting_currency": "JPY"},
    "TDK CORP": {"ticker": "6762", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6762.T", "reporting_currency": "JPY"},
    "THK CO LTD": {"ticker": "6481", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6481.T", "reporting_currency": "JPY"},
    "TOKAI RIKA CO LTD": {"ticker": "6995", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6995.T", "reporting_currency": "JPY"},
    "TOPY INDUSTRIES LTD": {"ticker": "7231", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7231.T", "reporting_currency": "JPY"},
    "TOYODA GOSEI CO LTD": {"ticker": "7282", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7282.T", "reporting_currency": "JPY"},
    "TOYOTA BOSHOKU CORP": {"ticker": "3116", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "3116.T", "reporting_currency": "JPY"},
    "TOYOTA INDUSTRIES CORP": {"ticker": "6201", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6201.T", "reporting_currency": "JPY"},
    "TSUBAKIMOTO CHAIN CO": {"ticker": "6371", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6371.T", "reporting_currency": "JPY"},
    "TSUBAKI NAKASHIMA CO LTD": {"ticker": "6464", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6464.T", "reporting_currency": "JPY"},
    "UCHIYAMA MANUFACTURING CORP": {"ticker": "6059", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6059.T", "reporting_currency": "JPY"},
    "UACJ CORP": {"ticker": "5741", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5741.T", "reporting_currency": "JPY"},
    "YOKOHAMA RUBBER CO LTD, THE": {"ticker": "5101", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5101.T", "reporting_currency": "JPY"},
    "YOKOWO CO LTD": {"ticker": "6975", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "6975.T", "reporting_currency": "JPY"},
    "YOROZU CORP": {"ticker": "7290", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7290.T", "reporting_currency": "JPY"},
    "TOYO TIRE CORPORATION": {"ticker": "5105", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "5105.T", "reporting_currency": "JPY"},
    # ── Korea (KRX, KRW) ────────────────────────────────────────────────────
    "CTR CO LTD": {"ticker": "036570", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "036570.KS", "reporting_currency": "KRW"},
    "DEPO AUTO PARTS IND CO LTD": {"ticker": "6600", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "6600.KS", "reporting_currency": "KRW"},
    "HANKOOK & COMPANY CO LTD": {"ticker": "000240", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "000240.KS", "reporting_currency": "KRW"},
    "HWASEUNG CORP CO LTD": {"ticker": "013520", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "013520.KS", "reporting_currency": "KRW"},
    "HYUNDAI WIA CORP": {"ticker": "011210", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "011210.KS", "reporting_currency": "KRW"},
    "ILJIN GLOBAL CO LTD": {"ticker": "014830", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "014830.KS", "reporting_currency": "KRW"},
    "JINHAP CO LTD": {"ticker": "051980", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "051980.KS", "reporting_currency": "KRW"},
    "LG CHEM LTD": {"ticker": "051910", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "051910.KS", "reporting_currency": "KRW"},
    "LG ELECTRONICS INC": {"ticker": "066570", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "066570.KS", "reporting_currency": "KRW"},
    "LS CORP": {"ticker": "006260", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "006260.KS", "reporting_currency": "KRW"},
    "MINTH GROUP LTD": {"ticker": "004255", "exchange": "HKEx", "data_source": "Other", "yahoo_symbol": "004255.HK", "reporting_currency": "HKD"},
    "SK INNOVATION CO LTD": {"ticker": "096770", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "096770.KS", "reporting_currency": "KRW"},
    "SL CORP": {"ticker": "005850", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "005850.KS", "reporting_currency": "KRW"},
    "SUNGWOO HITECH CO LTD": {"ticker": "015750", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "015750.KS", "reporting_currency": "KRW"},
    "TAEYANG METAL INDUSTRIAL CO LTD": {"ticker": "004100", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "004100.KS", "reporting_currency": "KRW"},
    "WOORY INDUSTRIAL HOLDINGS CO LTD": {"ticker": "072470", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "072470.KS", "reporting_currency": "KRW"},
    # ── Europe ──────────────────────────────────────────────────────────────
    "AMS AG": {"ticker": "AMS", "exchange": "SIX", "data_source": "Europe", "yahoo_symbol": "AMSWF", "reporting_currency": "CHF"},
    "ARKEMA": {"ticker": "AKE", "exchange": "EPA", "data_source": "Europe", "yahoo_symbol": "AKE.PA", "reporting_currency": "EUR"},
    "BASF SE": {"ticker": "BAS", "exchange": "XETRA", "data_source": "Europe", "yahoo_symbol": "BAS.DE", "reporting_currency": "EUR"},
    "BODYCOTE PLC": {"ticker": "BOY", "exchange": "LON", "data_source": "Europe", "yahoo_symbol": "BOY.L", "reporting_currency": "GBP"},
    "COMPAGNIE DE SAINT-GOBAIN": {"ticker": "SGO", "exchange": "EPA", "data_source": "Europe", "yahoo_symbol": "SGO.PA", "reporting_currency": "EUR"},
    "CTEK AB (PUBL)": {"ticker": "CTEK", "exchange": "SSTO", "data_source": "Europe", "yahoo_symbol": "CTEK.ST", "reporting_currency": "SEK"},
    "ELRINGKLINGER AG": {"ticker": "ZIL2", "exchange": "XETRA", "data_source": "Europe", "yahoo_symbol": "ZIL2.DE", "reporting_currency": "EUR"},
    "HANWHA CORP": {"ticker": "000880", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "000880.KS", "reporting_currency": "KRW"},
    "HEXAGON COMPOSITES ASA": {"ticker": "HEX", "exchange": "OSE", "data_source": "Europe", "yahoo_symbol": "HEX.OL", "reporting_currency": "NOK"},
    "KENDRION NV": {"ticker": "KENDR", "exchange": "AEX", "data_source": "Europe", "yahoo_symbol": "KENDR.AS", "reporting_currency": "EUR"},
    "KONGSBERG AUTOMOTIVE ASA": {"ticker": "KOG", "exchange": "OSE", "data_source": "Europe", "yahoo_symbol": "KOG.OL", "reporting_currency": "NOK"},
    "NEXANS SA": {"ticker": "NEX", "exchange": "EPA", "data_source": "Europe", "yahoo_symbol": "NEX.PA", "reporting_currency": "EUR"},
    "NORMA GROUP SE": {"ticker": "NOEJ", "exchange": "XETRA", "data_source": "Europe", "yahoo_symbol": "NOEJ.DE", "reporting_currency": "EUR"},
    "PIRELLI & CO SPA": {"ticker": "PIRC", "exchange": "BIT", "data_source": "Europe", "yahoo_symbol": "PIRC.MI", "reporting_currency": "EUR"},
    "POLYTEC HOLDINGS AG": {"ticker": "POL", "exchange": "VIE", "data_source": "Europe", "yahoo_symbol": "POL.VI", "reporting_currency": "EUR"},
    "PRYSMIAN SPA": {"ticker": "PRY", "exchange": "BIT", "data_source": "Europe", "yahoo_symbol": "PRY.MI", "reporting_currency": "EUR"},
    "SENIOR PLC": {"ticker": "SNR", "exchange": "LON", "data_source": "Europe", "yahoo_symbol": "SNR.L", "reporting_currency": "GBP"},
    "SFS GROUP AG": {"ticker": "SFSN", "exchange": "SIX", "data_source": "Europe", "yahoo_symbol": "SFSN.SW", "reporting_currency": "CHF"},
    "SIKA AG": {"ticker": "SIKA", "exchange": "SIX", "data_source": "Europe", "yahoo_symbol": "SIKA.SW", "reporting_currency": "CHF"},
    "SSAB AB": {"ticker": "SSAB A", "exchange": "SSTO", "data_source": "Europe", "yahoo_symbol": "SSAB-A.ST", "reporting_currency": "SEK"},
    "STABILUS SA": {"ticker": "STM", "exchange": "XETRA", "data_source": "Europe", "yahoo_symbol": "STM.DE", "reporting_currency": "EUR"},
    "TI FLUID SYSTEMS PLC": {"ticker": "TIFS", "exchange": "LON", "data_source": "Europe", "yahoo_symbol": "TIFS.L", "reporting_currency": "GBP"},
    "THULE GROUP AB": {"ticker": "THULE", "exchange": "SSTO", "data_source": "Europe", "yahoo_symbol": "THULE.ST", "reporting_currency": "SEK"},
    "TRELLEBORG AB": {"ticker": "TREL B", "exchange": "SSTO", "data_source": "Europe", "yahoo_symbol": "TREL-B.ST", "reporting_currency": "SEK"},
    "TT ELECTRONICS PLC": {"ticker": "TTG", "exchange": "LON", "data_source": "Europe", "yahoo_symbol": "TTG.L", "reporting_currency": "GBP"},
    # ── US ───────────────────────────────────────────────────────────────────
    "UNITED STATES STEEL CORP": {"ticker": "X", "exchange": "NYSE", "data_source": "US"},
    "JOHNSON ELECTRIC HOLDINGS LIMITED": {"ticker": "JELCY", "exchange": "OTC", "data_source": "Other", "yahoo_symbol": "JELCY", "reporting_currency": "USD"},
    # ── Other (Mexico, India, China, Taiwan, HK) ─────────────────────────────
    "RASSINI SAB DE CV": {"ticker": "RASSINI", "exchange": "BMV", "data_source": "Other", "yahoo_symbol": "RASSINI.MX", "reporting_currency": "MXN"},
    "GRUPO INDUSTRIAL SALTILLO SA DE CV": {"ticker": "GISSA", "exchange": "BMV", "data_source": "Other", "yahoo_symbol": "GISSA.MX", "reporting_currency": "MXN"},
    "BHARAT FORGE LTD": {"ticker": "BHARATFORG", "exchange": "NSE", "data_source": "Other", "yahoo_symbol": "BHARATFORG.NS", "reporting_currency": "INR"},
    "HINDALCO INDUSTRIES LTD": {"ticker": "HINDALCO", "exchange": "NSE", "data_source": "Other", "yahoo_symbol": "HINDALCO.NS", "reporting_currency": "INR"},
    "SUPRAJIT ENGINEERING LTD": {"ticker": "SUPRAJIT", "exchange": "NSE", "data_source": "Other", "yahoo_symbol": "SUPRAJIT.NS", "reporting_currency": "INR"},
    "SUNDRAM FASTENERS LTD": {"ticker": "SUNDRMFAST", "exchange": "NSE", "data_source": "Other", "yahoo_symbol": "SUNDRMFAST.NS", "reporting_currency": "INR"},
    "TUPY S/A": {"ticker": "TUPY3", "exchange": "B3", "data_source": "Other", "yahoo_symbol": "TUPY3.SA", "reporting_currency": "BRL"},
    "IOCHPE MAXION SA": {"ticker": "MYPK3", "exchange": "B3", "data_source": "Other", "yahoo_symbol": "MYPK3.SA", "reporting_currency": "BRL"},
    "CIE AUTOMOTIVE SA": {"ticker": "CIE", "exchange": "BME", "data_source": "Europe", "yahoo_symbol": "CIE.MC", "reporting_currency": "EUR"},
    "CHENG SHIN RUBBER INDUSTRIAL CO LTD": {"ticker": "2105", "exchange": "TPE", "data_source": "Other", "yahoo_symbol": "2105.TW", "reporting_currency": "TWD"},
    "FUYAO GLASS INDUSTRY GROUP CO LTD": {"ticker": "3606", "exchange": "HKG", "data_source": "Other", "yahoo_symbol": "3606.HK", "reporting_currency": "HKD"},
    "GUANGDONG HONGTU TECHNOLOGY HOLDING": {"ticker": "002101", "exchange": "SHE", "data_source": "Other", "yahoo_symbol": "002101.SZ", "reporting_currency": "CNY"},
    "NINGBO JOYSON ELECTRONIC CORP": {"ticker": "600699", "exchange": "SSE", "data_source": "Other", "yahoo_symbol": "600699.SS", "reporting_currency": "CNY"},
    "NINGBO HUAXIANG ELECTRONIC CO LTD": {"ticker": "002048", "exchange": "SHE", "data_source": "Other", "yahoo_symbol": "002048.SZ", "reporting_currency": "CNY"},
    "NINGBO JIFENG AUTO PARTS CO LTD": {"ticker": "603997", "exchange": "SSE", "data_source": "Other", "yahoo_symbol": "603997.SS", "reporting_currency": "CNY"},
    "SHANGHAI BAOLONG AUTOMOTIVE CORP": {"ticker": "603197", "exchange": "SSE", "data_source": "Other", "yahoo_symbol": "603197.SS", "reporting_currency": "CNY"},
    "XIAMEN HONGFA ELECTROACOUSTIC CO": {"ticker": "601137", "exchange": "SSE", "data_source": "Other", "yahoo_symbol": "601137.SS", "reporting_currency": "CNY"},
    "XIN POINT HOLDINGS LTD": {"ticker": "1571", "exchange": "HKEx", "data_source": "Other", "yahoo_symbol": "1571.HK", "reporting_currency": "HKD"},
    "ZHEJIANG SANHUA INTELLIGENT CONTROL": {"ticker": "002050", "exchange": "SHE", "data_source": "Other", "yahoo_symbol": "002050.SZ", "reporting_currency": "CNY"},
    "ZHEJIANG WANFENG AUTO WHEEL CO LTD": {"ticker": "002085", "exchange": "SHE", "data_source": "Other", "yahoo_symbol": "002085.SZ", "reporting_currency": "CNY"},
    "ZHEJIANG YINLUN MACHINERY CO LTD": {"ticker": "002126", "exchange": "SHE", "data_source": "Other", "yahoo_symbol": "002126.SZ", "reporting_currency": "CNY"},
    # HL MANDO: Korea
    "HL MANDO CORPORATION": {"ticker": "204320", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "204320.KS", "reporting_currency": "KRW"},
    # INFAC: Korea
    "INFAC CORPORATION": {"ticker": "023810", "exchange": "KRX", "data_source": "Japan_Korea", "yahoo_symbol": "023810.KS", "reporting_currency": "KRW"},
    # HI-LEX: Japan subsidiary, use parent or Japan ticker if listed
    "HI-LEX CORP": {"ticker": "7279", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "7279.T", "reporting_currency": "JPY"},
    "PARKER CORP": {"ticker": "9845", "exchange": "TYO", "data_source": "Japan_Korea", "yahoo_symbol": "9845.T", "reporting_currency": "JPY"},
}
# fmt: on
